"use client"

import { createContext, useContext, useEffect, useMemo, useState } from "react"

type Lang = "en" | "ar"

const LanguageContext = createContext<{ lang: Lang; setLang: (_lang: Lang) => void }>({ lang: "en", setLang: () => { } })
const ENGLISH_COPY: Record<string, string> = {
  "Corporate hero description": "Reliable on-site repair and maintenance for your company devices, delivered directly at your workplace across the UAE.",
  "Critical industries description": "Specialized field-service infrastructure for organizations where downtime is not an option.",
  "Corporate form description": "Tell us what your organization needs and our corporate team will contact you within 30 minutes.",
  "Corporate CTA description": "Upgrade to priority on-site maintenance with certified technicians, secure handling, and clear service-level commitments.",
  "Dedicated Account Manager Desc": "One dedicated contact who understands your sites, assets, and service history.",
  "Priority Service Desc": "Fast-track dispatch and repair scheduling for business-critical requests.",
  "On-Site Repairs Desc": "Certified technicians come directly to your workplace, reducing downtime and transport risk.",
  "Maintenance Contracts Desc": "Flexible monthly and annual plans designed around your fleet and operating hours.",
  "Asset Reporting Desc": "Clear reports covering device condition, faults, repairs, and recommended next actions.",
  "Data Security Desc": "Strict handling protocols protect company devices and sensitive business information.",
  "Our Mission Desc": "Deliver fast, reliable on-site repairs that save customers time and keep their technology working.",
  "Customer First Desc": "We put customer satisfaction first through clear communication, respectful service, and dependable support.",
  "Quality Guarantee Desc": "We use original or high-quality parts and back eligible repairs with a clear service warranty.",
}
const DICTIONARY: Record<string, string> = {
  "Need Help?": "هل تحتاج إلى مساعدة؟",
  "Chat with us on WhatsApp for quick assistance with your booking!": "تواصل معنا عبر واتساب للحصول على مساعدة سريعة مع الحجز!",
  "We're Online": "نحن متصلون الآن",
  "Serving All of Abu Dhabi": "نخدم جميع مناطق أبوظبي",
  "Screen replacement, battery, charging port, camera, speaker/mic fix, and software issues.": "استبدال الشاشة، البطارية، منفذ الشحن، الكاميرا، إصلاح السماعة/الميكروفون، ومشاكل البرمجيات.",
  "Fan cleaning, keyboard replacement, screen repair, port fixes, Windows installation.": "تنظيف المروحة، استبدال لوحة المفاتيح، إصلاح الشاشة، إصلاح المنافذ، وتثبيت ويندوز.",
  "Ink & toner issues, paper jam fix, cleaning, maintenance, and connectivity fixes.": "مشاكل الحبر، إصلاح انحشار الورق، التنظيف، الصيانة، وإصلاحات الاتصال.",
  "Backlight issues, HDMI/DisplayPort fix, flickering, no display, and dead pixels.": "مشاكل الإضاءة الخلفية، إصلاح HDMI/DisplayPort، الوميض، عدم العرض، والبكسلات التالفة.",
  "Power, no display, overheating, RAM/SSD, GPU, motherboard, Windows.": "مشاكل الطاقة، عدم العرض، ارتفاع الحرارة، RAM/SSD، كرت الشاشة، اللوحة الأم، وويندوز.",
  "TV not turning on, lines on screen, HDMI port repair, sound issues, software fix.": "التلفزيون لا يعمل، خطوط على الشاشة، إصلاح منفذ HDMI، مشاكل الصوت، وإصلاح البرمجيات.",
  "Screen replacement, battery replacement, crown repair, sensor and pairing issues.": "استبدال الشاشة، استبدال البطارية، إصلاح التاج، مشاكل المستشعر والاقتران.",
  "Full installation, DVR/NVR setup, camera fixes, night vision, WiFi connectivity.": "تركيب كامل، إعداد DVR/NVR، إصلاح الكاميرات، الرؤية الليلية، واتصال WiFi.",
  "Professional TV wall mount installation, smart TV setup, and cable management.": "تركيب احترافي للتلفزيون على الحائط، إعداد التلفزيون الذكي، وإدارة الكابلات.",
  "PlayStation & Xbox: HDMI port, overheating fix, disc drive, controller sync issues.": "بلايستيشن وإكس بوكس: منفذ HDMI، إصلاح الحرارة، إصلاح محرك الأقراص، ومشاكل مزامنة اليد.",
  Services: "الخدمات",
  "Enterprise-grade On-Site Repair": "خدمة إصلاح ميداني بمستوى الشركات",
  Corporate: "الشركات",
  "Repair Solutions": "حلول الإصلاح",
  "Corporate hero description": "خدمات إصلاح احترافية وموثوقة لأجهزة الشركات — تُقدَّم مباشرة في موقع عملك داخل الإمارات.",
  "Priority SLA": "اتفاقية مستوى خدمة أولوية",
  "Guaranteed response times": "أوقات استجابة مضمونة",
  "Secure Handling": "تعامل آمن",
  "Data privacy compliant": "متوافق مع خصوصية البيانات",
  "Contract-Based": "عقود خدمة",
  "Flexible monthly plans": "خطط شهرية مرنة",
  "24/7 Ops": "تشغيل على مدار الساعة",
  "Critical infrastructure support": "دعم البنية التحتية الحساسة",
  "Request Partnership": "طلب شراكة",
  "Book Technician": "احجز فنيًا",
  Response: "الاستجابة",
  Techs: "الفنيون",
  "Devices/Mo": "جهاز/شهر",
  "Built for": "حل موثوق",
  "Critical Industries": "للقطاعات التي لا تحتمل الخطأ",
  "Critical industries description": "بنية إصلاح ميدانية متخصصة للقطاعات التي لا تحتمل التوقف.",
  "The entities we deal with": "الجهات التي نتعامل معها",
  "Displays & Signage": "الشاشات واللافتات",
  "Priority Support": "دعم أولوية",
  "Ready to Upgrade Your Corporate Maintenance?": "هل أنت مستعد لترقية صيانة شركتك؟",
  "Corporate CTA description": "نوفر خدمات إصلاح وصيانة في الموقع لعملاء الشركات وفق اتفاقية أولوية. جميع الإصلاحات ينفذها فنّيون معتمدون مع التزام كامل بخصوصية البيانات ومعايير الأمان.",
  "Get a Quote": "احصل على عرض",

  "24/7": "على مدار 24/7",
  "All UAE": "جميع أنحاء الإمارات",
  "Call Us (24/7)": "اتصل بنا (24/7)",
  "WhatsApp Support": "دعم واتساب",
  "Chat Instantly": "دردشة فورية",
  "Email Us": "راسلنا عبر البريد",
  "Corporate Maintenance Contracts": "عقود صيانة للشركات",
  "Monthly Contract": "عقد شهري",
  "Unlimited visits": "زيارات غير محدودة",
  "Fixed monthly rate": "رسوم شهرية ثابتة",
  "Priority repairs": "أولوية في الإصلاح",
  "Yearly Contract": "عقد سنوي",
  "Discounted pricing": "أسعار مخفضة",
  "Full IT Support": "دعم تقني شامل",
  "Replacement options": "خيارات الاستبدال",
  "Pay-Per-Visit": "الدفع لكل زيارة",
  "One-time repair": "إصلاح مرة واحدة",
  "Standard rates": "أسعار قياسية",
  "Ideal for occasional needs": "مثالي للاحتياجات العرضية",
  "POPULAR": "شائع",
  "avg response": "متوسط الاستجابة",
  "Priority dispatch for corporate clients": "أولوية الإرسال لعملاء الشركات",
  "technicians": "فنيين",
  "Coverage across all UAE regions": "تغطية جميع مناطق الإمارات",
  "devices/month": "جهاز/شهر",
  "Enterprise-grade servicing capacity": "قدرة خدمة بمستوى الشركات",
  "Track Order": "تتبّع الطلب",
  "Quick Links": "روابط سريعة",
  "About Us": "نبذة عنا",
  About: "من نحن",
  Contact: "تواصل معنا",
  "Call Now": "اتصل الآن",
  Menu: "القائمة",
  Navigation: "التنقل",
  "Support Chat": "دردشة الدعم",
  "We reply fast on WhatsApp": "نرد بسرعة عبر واتساب",
  "Chat with Support": "تواصل مع الدعم",
  "Open WhatsApp": "افتح واتساب",
  "Type your message...": "اكتب رسالتك...",
  "Hello, I want to book a technician.": "مرحبًا، أود حجز فني.",
  "Hello, I want to track my order.": "مرحبًا، أريد تتبّع طلبي.",
  "Enter your tracking number to see the live status of your repair order.": "أدخل رقم التتبع الخاص بك لمعرفة الحالة المباشرة لطلب الإصلاح.",
  "Hello, I need corporate support.": "مرحبًا، أحتاج دعم الشركات.",
  "How much?": "كم التكلفة؟",
  "Hello! I'm booking a repair and would like a price estimate.": "مرحبًا! أقوم بحجز إصلاح وأود الحصول على تقدير للأسعار.",
  "Same-day?": "خدمة في نفس اليوم؟",
  "Hello! Do you offer same-day service for this repair?": "مرحبًا! هل توفرون خدمة في نفس اليوم لهذا الإصلاح؟",
  "Warranty?": "هل يوجد ضمان؟",
  "Hello! What warranty do you offer on repairs?": "مرحبًا! ما هو الضمان الذي توفرونه على الإصلاحات؟",
  "Price for": "سعر لـ",
  "Hello! I'd like to know the price for {device} repair.": "مرحبًا! أود أن أعرف سعر إصلاح {device}.",
  "Booking help available": "مساعدة في الحجز متاحة",
  "We can help with booking step {step}": "يمكننا مساعدتك في خطوة الحجز {step}",
  "Home": "الرئيسية",
  "Hello! I need support.": "مرحبًا! أحتاج إلى دعم.",
  "Corporate Support": "دعم الشركات",
  "Corporate Services": "خدمات الشركات",
  "Our Main Services": "خدماتنا الرئيسية",
  "Professional on-site repair services for all your devices": "خدمات إصلاح ميدانية احترافية لجميع أجهزتك",
  "We Come to You": "نصل إليك",
  "Best On-Site Repair in Abu Dhabi": "أفضل خدمة إصلاح في موقعك بأبوظبي",
  "Fast, professional, and guaranteed repairs at your home or office — anywhere in Abu Dhabi. Specialists in mobile, laptop, printer, and CCTV maintenance.": "خدمات إصلاح سريعة ومحترفة ومضمونة في منزلك أو مكتبك — نغطي جميع مناطق أبوظبي. نحن متخصصون في صيانة الهواتف، اللابتوبات، الطابعات وكاميرات المراقبة.",
  "Mobile Phone Repair": "إصلاح الهواتف المحمولة",
  "Laptop Repair": "إصلاح اللابتوب",
  "Printer Repair": "إصلاح الطابعات",
  "Monitor Repair": "إصلاح الشاشات",
  "PC / Desktop Computer Repair": "إصلاح أجهزة الكمبيوتر المكتبية",
  "TV Repair": "إصلاح التلفزيونات",
  "Apple Watch Repair": "إصلاح ساعة آبل",
  "CCTV Installation & Repair": "تركيب وإصلاح كاميرات المراقبة",
  "CCTV Installation": "تركيب كاميرات المراقبة",
  "TV Wall Mounting": "تركيب التلفزيون على الحائط",
  "Network Installation & Maintenance": "تركيب وصيانة الشبكات",
  "LAN & Wi-Fi Installation": "تركيب شبكات LAN و Wi-Fi",
  "Router & Switch Configuration": "إعداد الراوترات والسويتشات",
  "Network Speed & Stability Optimization": "تحسين سرعة واستقرار الشبكة",
  "Signal Strength Improvement": "حل مشاكل الانقطاع وضعف الإشارة",
  "Periodic Maintenance & Support": "صيانة دورية ودعم فني عند الطلب",
  "VPN / Remote Access Setup": "إعداد شبكات VPN والوصول عن بعد",
  "Cabling & Infrastructure (Cat6/Fiber)": "تمديد الكابلات والبنية التحتية (Cat6/ألياف)",
  "Gaming Console Repair": "إصلاح أجهزة الألعاب",
  "Services We Offer": "الخدمات المتاحة",
  "Brands We Service": "العلامات التجارية التي نخدمها",
  "Popular models we repair:": "نماذج شائعة نقوم بإصلاحها:",
  "+ many more": "+ المزيد",
  "Book a technician now and get your device repaired at your doorstep. Fast, reliable, and guaranteed.": "احجز فنيًا الآن ليصل إليك ويصلح جهازك في موقعك. خدمة سريعة، موثوقة، ومضمونة.",
  "Rate us on Google": "قيّمنا على Google",
  "Why Choose KBI?": "لماذا تختار KBI؟",
  "Why Choose Us": "لماذا تختارنا؟",
  "We're committed to providing the best repair experience in Abu Dhabi with professional on-site service.": "ملتزمون بتقديم أفضل تجربة إصلاح في أبوظبي من خلال خدمة ميدانية احترافية في موقعك.",
  "Certified Experts": "خبراء معتمدون",
  "Our team consists of highly trained and certified technicians with years of experience.": "يتكون فريقنا من فنيين مدربين تدريبًا عاليًا ومعتمدين مع سنوات من الخبرة.",
  "Same-Day Service": "خدمة في نفس اليوم",
  "We arrive at your location - home or office - the same day you book.": "نصل إلى موقعك - المنزل أو المكتب - في نفس اليوم الذي تحجز فيه.",
  "Free Diagnostics": "فحص مجاني",
  "No fix, no fee. Diagnostic check is free if you proceed with the repair.": "لا إصلاح، لا رسوم. الفحص التشخيصي مجاني إذا واصلت الإصلاح.",
  "Genuine Parts": "قطع غيار أصلية",
  "We only use high-quality, genuine parts for all our repairs.": "نستخدم فقط قطع غيار أصلية وعالية الجودة لجميع إصلاحاتنا.",
  "Warranty Included": "الضمان مشمول",
  "Transparent Pricing": "تسعير شفاف",
  "All our repairs come with a solid 3-6 months warranty for your peace of mind.": "تأتي جميع إصلاحاتنا بضمان قوي لمدة 3-6 أشهر لراحتك.",
  "Know the cost upfront. No hidden fees or surprises after the work is done.": "اعرف التكلفة مقدمًا. لا توجد رسوم مخفية أو مفاجآت بعد انتهاء العمل.",
  "About KBI": "عن KBI",
  "To provide fast, reliable, and professional on-site repair services that save our customers time and hassle.": "تقديم خدمات إصلاح ميدانية سريعة وموثوقة واحترافية توفر على عملائنا الوقت والجهد.",
  "We prioritize customer satisfaction above all else. Your trust is our most valuable asset, and we work hard to earn it every day.": "نضع رضا العميل فوق كل شيء. ثقتكم هي أهم ما لدينا، ونعمل يوميًا لنستحقها.",
  "We use only original or high-quality replacement parts and back all our repairs with a solid warranty for your peace of mind.": "نستخدم قطع غيار أصلية أو عالية الجودة، ونضمن جميع الإصلاحات بضمان قوي لراحة بالك.",
  "Al Reem Island": "جزيرة الريم",
  "Khalifa City": "مدينة خليفة",
  "MBZ City": "مدينة محمد بن زايد",
  "Al Shamkha": "الشامخة",
  "Al Reef": "الريف",
  "Al Nahyan": "آل نهيان",
  "Tourist Club Area": "منطقة النادي السياحي",
  "Musaffah": "مصفح",
  "Shakhbout City": "مدينة شخبوط",
  "Al Ain Road": "طريق العين",
  "Corniche": "الكورنيش",
  "Marina Mall Area": "منطقة مارينا مول",
  "Al Bateen": "البطين",
  "Al Mushrif": "المشرف",
  "Al Khalidiyah": "الخالدية",
  "Al Karama": "الكرامة",
  "Al Rowdah": "الروضة",
  "Al Muroor": "المرور",
  "Saadiyat Island": "جزيرة السعديات",
  "Yas Island": "جزيرة ياس",
  "Masdar City": "مدينة مصدر",
  "Al Samha": "السمحة",
  "Al Bahia": "الباهية",
  "Al Rahba": "الرحبة",
  "Al Shahama": "الشهامة",
  "Baniyas": "بني ياس",
  "Al Shawamekh": "الشوامخ",
  "Al Falah": "الفلاح",
  "Hydra Village": "هيدرا فيليج",
  "All Abu Dhabi": "جميع مناطق أبوظبي",
  Device: "الجهاز",
  Brand: "العلامة التجارية",
  Model: "الموديل",
  Issue: "المشكلة",
  Details: "التفاصيل",
  "Select Your Device": "اختر جهازك",
  "Add Another Device": "أضف جهازًا آخر",
  "Continue to Details": "المتابعة إلى التفاصيل",
  "One visit, all devices • Single tracking number • Priority scheduling": "زيارة واحدة لجميع الأجهزة • رقم تتبّع واحد • جدولة أولوية",
  "How Our Service Works": "كيف تعمل خدمتنا",
  "Simple, fast, and hassle-free repair process": "عملية إصلاح بسيطة وسريعة بدون تعقيد",
  "Book via site or WhatsApp with device details": "احجز عبر الموقع أو واتساب مع تفاصيل الجهاز",
  "We assign a certified technician for your request": "نقوم بتعيين فني معتمد لطلبك",
  "We Come to Your Location": "نأتي إلى موقعك",
  "Technician arrives at your home or office": "الفني يصل إلى منزلك أو مكتبك",
  "Instant Diagnosis": "تشخيص فوري",
  "Free diagnosis to identify the problem": "تشخيص مجاني لتحديد المشكلة",
  "Complete Repair": "إتمام الإصلاح",
  "Professional repair using high-quality parts": "إصلاح احترافي باستخدام قطع عالية الجودة",
  "Pay After Repair": "الدفع بعد الإصلاح",
  "Pay only when you are satisfied with the work": "تدفع فقط عند رضاك عن العمل",
  "Found orders": "تم العثور على طلبات",
  "Back to list": "العودة إلى القائمة",
  "Call Support": "اتصل بالدعم",
  "ETA": "الوقت المتوقع",
  "Copy order ID": "نسخ رقم الطلب",
  "Assigning Specialist...": "جاري تعيين فني مختص...",
  "Same-day Service": "خدمة في نفس اليوم",
  "Searching...": "جاري البحث...",
  "Enter registered phone number": "أدخل رقم الهاتف المسجل",
  "Order Tracking": "تتبع الطلب",
  "Order ID or phone number": "رقم الطلب أو الهاتف",
  "Enter order ID or phone number": "أدخل رقم الطلب أو رقم الهاتف",
  "Tip: Search by order ID (KBI-XXXX) or phone number": "نصيحة: يمكنك البحث برقم الطلب أو رقم الهاتف",
  "Professional Repair Services": "خدمات إصلاح احترافية",
  "Our": "خدماتنا",
  "Our Services": "خدماتنا",
  "Professional on-site repair for all your devices. Choose your device below to see the services we offer and brands we support.": "إصلاح ميداني احترافي لجميع أجهزتك. اختر جهازك أدناه للاطلاع على الخدمات التي نقدمها والعلامات التجارية التي ندعمها.",
  "Continue with": "المتابعة مع",
  "Device(s)": "جهاز/أجهزة",
  "Devices Added": "الأجهزة المُضافة",
  "Select Model": "اختر الموديل",
  "Select Issue": "اختر المشكلة",
  "Book a": "احجز",
  Technician: "فني",
  "Select your device, tell us the problem, and we'll send a certified technician to your location.": "اختر جهازك، وأخبرنا بالمشكلة، وسنرسل فنيًا معتمدًا إلى موقعك.",
  Type: "النوع",
  "Your Details": "بياناتك",
  "Full Name *": "الاسم الكامل *",
  "Phone Number *": "رقم الهاتف *",
  WhatsApp: "واتساب",
  Address: "العنوان",
  "Address / Location *": "العنوان / الموقع *",
  "Preferred Date": "التاريخ المفضل",
  "Preferred Time": "الوقت المفضل",
  "Additional Notes": "ملاحظات إضافية",
  "Your full name": "اسمك الكامل",
  "WhatsApp number (optional)": "رقم واتساب (اختياري)",
  "Your address in Abu Dhabi": "عنوانك في أبوظبي",
  "Describe the issue in more detail (optional)": "صف المشكلة بمزيد من التفصيل (اختياري)",
  "Order Created Successfully!": "تم إنشاء الطلب بنجاح!",
  "Your Tracking Number": "رقم التتبّع الخاص بك",
  "Track Your Order": "تتبّع طلبك",
  "Chat on WhatsApp": "محادثة عبر واتساب",
  "Order Summary": "ملخص الطلب",
  "Add More": "أضف المزيد",
  "Create Order": "إنشاء الطلب",
  "By booking, you agree to our terms. Payment is only after successful repair.": "بالحجز، فإنك توافق على الشروط. الدفع فقط بعد إتمام الإصلاح بنجاح.",
  "Order Not Found": "لم يتم العثور على الطلب",
  "We couldn't find an order with tracking number": "لم نعثر على طلب برقم التتبّع",
  "Please check and try again.": "يرجى التحقق والمحاولة مرة أخرى.",
  "Contact Support": "تواصل مع الدعم",
  "Hotline 24/7": "الخط الساخن 24/7",
  "Abu Dhabi, UAE": "أبوظبي، الإمارات",
  "Tracking Number": "رقم التتبّع",
  "Order Date": "تاريخ الطلب",
  "Order Status": "حالة الطلب",
  "Order Created": "تم إنشاء الطلب",
  "Technician Assigned": "تم تعيين فني",
  "Technician On the Way": "الفني في الطريق",
  "Diagnostic in Progress": "جاري الفحص",
  "Repair in Progress": "جاري الإصلاح",
  "Quality Check": "فحص الجودة",
  "Completed / Delivered": "مكتمل / تم التسليم",
  "Your order has been received": "تم استلام طلبك",
  "A technician has been assigned to your order": "تم تعيين فني لطلبك",
  "Your technician is heading to your location": "الفني في طريقه إلى موقعك",
  "We're diagnosing your device": "جارٍ فحص جهازك",
  "Your device is being repaired": "جارٍ إصلاح جهازك",
  "Final quality assurance check": "فحص الجودة النهائي",
  "Your repair is complete!": "تم إكمال الإصلاح!",
  "Mobile Phone": "هاتف جوال",
  Laptop: "حاسوب محمول",
  "PC / Desktop Computer": "حاسوب مكتبي",
  "iPad / Tablet": "جهاز لوحي/آيباد",
  TV: "تلفزيون",
  CCTV: "كاميرات مراقبة",
  "PlayStation / Xbox": "أجهزة ألعاب الفيديو",
  Printer: "طابعة",
  "Apple Watch": "ساعة أبل",
  "TV Installation": "تركيب أجهزة التلفزيون",
  "Screen Replacement": "استبدال الشاشة",
  "Battery Replacement": "استبدال البطارية",
  "Charging Port Repair": "إصلاح منفذ الشحن",
  "Camera Replacement": "استبدال الكاميرا",
  "Speaker / Mic Fix": "إصلاح السماعة/الميكروفون",
  "Software Issues": "مشاكل برمجية",
  "Software / System Issue": "مشكلة في النظام/البرمجيات",
  "Software / System Issues": "مشاكل النظام/البرمجيات",
  "Water Damage": "أضرار المياه",
  "Back Glass Replacement": "استبدال الزجاج الخلفي",
  "Fan Cleaning & Thermal Paste": "تنظيف المروحة وتغيير المعجون الحراري",
  "Keyboard Replacement": "استبدال لوحة المفاتيح",
  "USB / HDMI Port Repair": "إصلاح منافذ USB/HDMI",
  "HDMI Port Repair": "إصلاح منفذ HDMI",
  "Windows Installation": "تثبيت ويندوز",
  "Overheating Fix": "حل مشكلة السخونة الزائدة",
  "SSD Upgrade": "ترقية SSD",
  "SSD/RAM Upgrade": "ترقية SSD/RAM",
  "Motherboard Repair": "إصلاح اللوحة الأم",
  "Sound Issues": "مشاكل الصوت",
  "Backlight Issues": "مشاكل الإضاءة الخلفية",
  "Backlight Repair": "إصلاح الإضاءة الخلفية",
  "Flickering / No Display": "وميض/لا توجد صورة",
  "Dead Pixels": "نقاط ميتة",
  "TV Not Turning On": "التلفزيون لا يعمل",
  "Lines on Screen": "خطوط على الشاشة",
  "Full CCTV Installation": "تركيب كامل لنظام المراقبة",
  "DVR / NVR Setup": "إعداد DVR/NVR",
  "Camera Not Working": "الكاميرا لا تعمل",
  "No Signal": "لا توجد إشارة",
  "Night Vision Issues": "مشاكل الرؤية الليلية",
  "WiFi / Connectivity Fix": "حل مشاكل الاتصال/واي فاي",
  "Add New Cameras": "إضافة كاميرات جديدة",
  "Camera Upgrade": "ترقية الكاميرات",
  "TV Wall Mount Installation": "تركيب التلفزيون على الحائط",
  "Smart TV Setup": "إعداد التلفزيون الذكي",
  "Cable Management": "تنظيم الكابلات",
  "Soundbar Installation": "تركيب مكبر الصوت",
  "Full Home Theater Setup": "إعداد كامل لنظام المسرح المنزلي",
  "Controller Sync Issues": "مشاكل مزامنة جهاز التحكم",
  "Disc Drive Repair": "إصلاح محرك الأقراص",
  "Crown Repair": "إصلاح التاج الرقمي",
  "Sensor Issues": "مشاكل المستشعرات",
  "Pairing Issues": "مشاكل الاقتران",
  "Other Model (Enter Manually)": "موديل آخر (أدخل يدويًا)",
  "Enter your model manually": "اكتب الموديل بنفسك",
  "Enter Model Name": "أدخل اسم الموديل",
  "Use This Model": "استخدام هذا الموديل",
  "Choose the Problem": "اختر المشكلة",
  "Choose the brand": "اختر العلامة التجارية",
  "Select Brand": "اختر العلامة",
  "Ink & Toner Issues": "مشاكل الحبر والتونر",
  "Laser Printer Repair": "إصلاح طابعات الليزر",
  "Cleaning & Maintenance": "تنظيف وصيانة",
  "Print Quality Issues": "مشاكل جودة الطباعة",
  "Inkjet Printer Repair": "إصلاح الطابعات النافثة للحبر",
  "Select Service": "اختر الخدمة",
  "~60 min": "حوالي 60 دقيقة",
  Detect: "تحديد الموقع",
  "Detecting...": "جارٍ تحديد الموقع...",
  "Location requires HTTPS. Please open via https or enter address manually.": "يتطلب تحديد الموقع اتصالًا آمنًا (HTTPS). افتح الصفحة عبر https أو أدخل العنوان يدويًا.",
  "Geolocation is not supported by your browser": "متصفحك لا يدعم تحديد الموقع.",
  "Failed to detect address. Please enter manually.": "تعذر تحديد العنوان. يرجى إدخاله يدويًا.",
  "Location permission denied. Please allow access or enter address manually.": "تم رفض إذن الموقع. يرجى السماح بالوصول أو إدخال العنوان يدويًا.",
  "Location unavailable. Please enter address manually.": "الموقع غير متاح. يرجى إدخال العنوان يدويًا.",
  "Failed to get location": "تعذر الحصول على الموقع.",
  "Location Type": "نوع الموقع",
  "Home Location": "المنزل",
  "Office Location": "المكتب",
  "Apartment / Villa Number": "رقم الشقة / الفيلا",
  Dashboard: "الرئيسية",
  "Dashboard Overview": "نظرة عامة",
  "Orders Management": "إدارة الطلبات",
  Technicians: "الفنيين",
  "Technicians Management": "إدارة الفنيين",
  "New Technician": "فني جديد",
  "Technician Details": "تفاصيل الفني",
  "Devices & Models & Issues": "الأجهزة والموديلات والمشاكل",
  "Contact Us Management": "إدارة التواصل",
  "Contact Messages": "رسائل التواصل",
  "Site Settings": "إعدادات الموقع",
  "Pages Content": "محتوى الصفحات",
  "Total Orders": "إجمالي الطلبات",
  "Orders In Progress": "طلبات قيد التنفيذ",
  "Completed Orders": "طلبات مكتملة",
  "Technicians Count": "عدد الفنيين",
  "Devices Supported": "الأجهزة المدعومة",
  "Today's New Orders": "طلبات جديدة اليوم",
  "Search": "بحث",
  "Filter by status": "تصفية حسب الحالة",
  "New Order": "طلب جديد",
  "Order ID": "رقم الطلب",
  "Customer Name": "اسم العميل",
  Phone: "الهاتف",
  "Issue Type": "نوع المشكلة",
  "Current Status": "الحالة الحالية",
  "Remaining Time": "الوقت المتبقي",
  "Assigned Technician": "الفني المعين",
  View: "عرض",
  Edit: "تعديل",
  Save: "حفظ",
  Cancel: "إلغاء",
  All: "الكل",
  "Order Details": "تفاصيل الطلب",
  Customer: "العميل",
  "Device Details": "تفاصيل الجهاز",
  "ETA (minutes)": "المدة المتوقعة (دقائق)",
  Notes: "ملاحظات",
  Price: "السعر",
  Discount: "خصم",
  Total: "الإجمالي",
  "View / Edit Order": "عرض / تعديل الطلب",
  "Change order status": "تغيير حالة الطلب",
  "Modify estimated completion time": "تعديل وقت الإتمام المتوقع",
  "Assign a technician": "تعيين فني",
  "View customer details": "عرض تفاصيل العميل",
  "View device details": "عرض تفاصيل الجهاز",
  "Edit manual info": "تعديل المعلومات يدويًا",
  "Save updates": "حفظ التحديثات",
  Name: "الاسم",
  Specialization: "التخصص",
  Status: "الحالة",
  Active: "نشط",
  Inactive: "غير نشط",
  "Current assigned jobs": "الأعمال الحالية",
  Add: "إضافة",
  Delete: "حذف",
  Update: "تحديث",
  "Devices List": "قائمة الأجهزة",
  "Models Management": "إدارة الموديلات",
  "Issues Management": "إدارة المشاكل",
  "Enable Other Model (Enter Manually)": "تفعيل موديل آخر (إدخال يدوي)",
  "Model Year Range": "نطاق سنة الموديل",
  "Contact Settings": "إعدادات التواصل",
  "Main Email": "البريد الإلكتروني الرئيسي",
  "WhatsApp Number": "رقم واتساب",
  "Support Phone Number": "رقم دعم العملاء",
  "Secondary Phone (optional)": "رقم إضافي (اختياري)",
  "Business Address": "عنوان العمل",
  "Working Hours": "ساعات العمل",
  "Service Areas": "مناطق الخدمة",
  "Save Settings": "حفظ الإعدادات",
  "Settings saved": "تم حفظ الإعدادات",

  Email: "البريد الإلكتروني",
  Subject: "الموضوع",
  Date: "التاريخ",
  StatusText: "الحالة",
  New: "جديد",
  Read: "مقروء",
  "View Message": "عرض الرسالة",
  "Message Body": "نص الرسالة",
  "Mark as Read": "وضع كمقروء",
  "Delete Message": "حذف الرسالة",
  "Business Name": "اسم العمل",
  "Main Phone": "الهاتف الرئيسي",
  "WhatsApp Link": "رابط واتساب",

  "Footer Text": "نص التذييل",
  "Footer Text (English)": "نص التذييل (بالإنجليزي)",
  "Footer Text (Arabic)": "نص التذييل (بالعربي)",
  "Address (English)": "العنوان (بالإنجليزي)",
  "Address (Arabic)": "العنوان (بالعربي)",
  "Allow Admin Registration": "السماح بتسجيل المشرفين",
  "* Enable \"Allow Admin Registration\" to let new admins create accounts on the login page. Disable it immediately after setup.": "* قم بتفعيل \"السماح بتسجيل المشرفين\" لتمكين المشرفين الجدد من إنشاء حسابات. قم بإيقافه مباشرة بعد الانتهاء.",
  "Service Areas List": "قائمة مناطق الخدمة",
  "Working Hours (Weekdays)": "ساعات العمل (أيام الأسبوع)",
  "Working Hours (Friday)": "ساعات العمل (الجمعة)",
  "Social Media Links": "روابط التواصل الاجتماعي",
  "Enable Digital Countdown": "تفعيل العد التنازلي الرقمي",
  "Enable Corporate Page": "تفعيل صفحة الشركات",
  "Pages Content Editor": "محرر محتوى الصفحات",
  "Home Page": "الصفحة الرئيسية",
  "Services Page": "صفحة الخدمات",
  "Corporate Services Page": "صفحة خدمات الشركات",
  "About Page": "صفحة من نحن",
  "Call-to-action Text": "نص الدعوة للإجراء",
  "Hardware: Power Supply Issue": "عطل مزوّد الطاقة",
  "Hardware: No Display": "لا توجد صورة",
  "Hardware: Overheating": "سخونة زائدة",
  "Hardware: CPU Fan Replacement": "استبدال مروحة المعالج",
  "Hardware: RAM Upgrade / Replacement": "ترقية/استبدال الذاكرة",
  "Hardware: SSD Upgrade / OS Install": "ترقية SSD / تثبيت النظام",
  "Hardware: GPU Issue / No Signal": "مشكلة بطاقة الرسومات/لا توجد إشارة",
  "Hardware: Motherboard Repair": "إصلاح اللوحة الأم",
  "Software: Windows Installation": "تثبيت ويندوز",
  "Software: Virus Removal": "إزالة الفيروسات",
  "Software: System Slow": "بطء النظام",
  "Software: Driver Issues": "مشاكل التعريفات",
  "Software: BIOS Errors": "أخطاء BIOS",
  "Physical: Broken Ports (USB / HDMI)": "منافذ تالفة (USB/HDMI)",
  "Physical: Front Panel Not Working": "المنافذ الأمامية لا تعمل",
  "Physical: PSU Noise": "ضجيج مزوّد الطاقة",
  "Device Icon": "أيقونة الجهاز",
  "Device Name": "اسم الجهاز",

  "General Information": "معلومات عامة",
  "Features": "المميزات",
  "Enable Order Countdown": "تفعيل العد التنازلي للطلب",
  "Enable Other Model (Manual Entry)": "تفعيل موديل آخر (إدخال يدوي)",

  "Upload an icon or a default placeholder will be used.": "قم برفع أيقونة، أو سيتم استخدام أيقونة افتراضية.",
  "Select Device": "اختر الجهاز",
  "New Brand Name": "اسم علامة جديد",
  "No brands found": "لا توجد علامات",
  "Brands Management": "إدارة العلامات",
  "Adding models for:": "إضافة موديلات لـ:",
  "New Model Name": "اسم موديل جديد",
  "No models found": "لا توجد موديلات",
  "Select a brand to manage models": "اختر علامة لإدارة الموديلات",
  "Issue Name": "اسم المشكلة",
  "Mins": "دقائق",
  "Duration:": "المدة:",
  "min": "دقيقة",
  "No issues found for this device": "لا توجد مشاكل لهذا الجهاز",
  "Time Remaining": "الوقت المتبقي",
  "e.g. Screen Replacement": "مثال: استبدال الشاشة",
  "Technician Dashboard": "لوحة تحكم الفني",
  "Active Jobs": "المهام النشطة",
  Featured: "مميز",
  "Book Now": "احجز الآن",
  "Professional wired and wireless network setup and configuration with performance optimization.": "تركيب وإعداد الشبكات السلكية واللاسلكية مع تحسين الأداء واستقرار الاتصال.",
  "Technical Support": "الدعم التقني",
  "Fast technical support to solve all hardware and system issues remotely or on-site.": "دعم فني سريع لحل جميع مشاكل الأجهزة والأنظمة عن بُعد أو في موقعك.",
  "Remote Technical Support": "دعم فني عن بُعد (Remote Support)",
  "Hardware & Software Diagnostics": "تشخيص وحل مشاكل الأجهزة والبرامج",
  "System & Network Setup": "إعداد الأنظمة والشبكات",
  "Virus Removal & Optimization": "إزالة الفيروسات وتحسين الأداء",
  "Phone & WhatsApp Support": "دعم فوري عبر الهاتف و WhatsApp",
  "Data Recovery": "استعادة البيانات",
  "Email & Cloud Setup": "إعداد البريد الإلكتروني والسحابة",
  "Assigned Orders": "الطلبات المعينة",
  "My Profile": "ملفي الشخصي",
  "Welcome back": "مرحبًا بعودتك",
  "View All Orders": "عرض كل الطلبات",
  "Completed Today": "المكتملة اليوم",
  "Total Assigned": "إجمالي المعين",
  "Lifetime orders": "كل الطلبات",
  "Recent Assigned Orders": "آخر الطلبات المعينة",
  "Loading orders...": "جاري تحميل الطلبات...",
  "No orders assigned yet.": "لا توجد طلبات معينة بعد.",
  "Manage your daily tasks": "إدارة مهامك اليومية",
  "Search by ID, Device, Customer...": "بحث بالرقم، الجهاز، العميل...",
  "Filter by Status": "تصفية حسب الحالة",
  "All Statuses": "كل الحالات",
  "No orders found matching your criteria.": "لا توجد طلبات تطابق بحثك.",
  "Assigned to you": "معين لك",
  "Navigate": "الملاحة",
  "Update Order Status": "تحديث حالة الطلب",
  "Select new status": "اختر الحالة الجديدة",
  "Waiting for Parts": "بانتظار قطع الغيار",
  "Work Notes": "ملاحظات العمل",
  "Add a note...": "أضف ملاحظة...",
  "Attachments": "المرفقات",
  "Sign Out": "تسجيل الخروج",
  "Average Rating": "متوسط التقييم",
  "Jobs Completed": "المهام المكتملة",
  "Specializations": "التخصصات",
  "Account Info": "معلومات الحساب",
  "Member Since": "عضو منذ",
  "Employee ID": "رقم الموظف",

  "Export CSV": "تصدير CSV",
  "Search orders...": "بحث عن الطلبات...",

  "Actions": "إجراءات",
  "Open menu": "فتح القائمة",
  "View Details": "عرض التفاصيل",
  "Assign Technician": "تعيين فني",
  "Delete Order": "حذف الطلب",
  "Previous": "السابق",
  "Next": "التالي",
  "Page": "صفحة",
  "of": "من",

  "Created": "تم الإنشاء",

  "No orders found": "لا توجد طلبات",
  "Unassigned": "غير معيّن",
  "Order Timeline": "الخط الزمني للطلب",
  "Order Placed": "تم إنشاء الطلب",
  "Order has been created": "تم إنشاء الطلب",
  "In Repair": "قيد الإصلاح",
  "Technician is working on the device": "الفني يعمل على الجهاز",
  "Repair Completed": "تم إكمال الإصلاح",
  "Device returned to customer": "تم تسليم الجهاز للعميل",
  "Order Cancelled": "تم إلغاء الطلب",
  "This order has been cancelled.": "هذا الطلب تم إلغاؤه.",
  "Detailed History": "سجل تفصيلي",
  "Just now": "الآن",
  "Contact Inbox": "البريد الوارد للتواصل",
  "Corporate Requests": "طلبات الشركات",
  "Management": "الإدارة",
  "Inbox": "البريد الوارد",
  "Configuration": "التهيئة",
  "Admin Panel": "لوحة الإدارة",
  "Repair Services": "خدمات الإصلاح",
  "Admin User": "مستخدم الإدارة",
  "Technician Portal": "بوابة الفني",
  "Log out": "تسجيل الخروج",
  "Profile": "الملف الشخصي",
  "Checking access": "جاري التحقق من الصلاحيات",
  "Add Technician": "إضافة فني",
  "Add New Technician": "إضافة فني جديد",
  "Enter technician details and permissions": "أدخل بيانات الفني والصلاحيات",
  "Update technician details and permissions": "تحديث بيانات الفني والصلاحيات",
  "Specialization (comma separated)": "التخصصات (مفصولة بفواصل)",

  "Save Changes": "حفظ التغييرات",
  "No technicians found": "لا يوجد فنيون",
  "Permissions": "الصلاحيات",
  "Messages": "الرسائل",

  "No messages": "لا توجد رسائل",
  "Select a message to read": "اختر رسالة لقراءتها",
  "Delete this message?": "هل تريد حذف هذه الرسالة؟",
  "Contact Information": "معلومات التواصل",
  "Email Address": "عنوان البريد الإلكتروني",
  "Phone Number": "رقم الهاتف",
  "Error saving settings": "خطأ في حفظ الإعدادات",
  "Status updated to": "تم تحديث الحالة إلى",
  "Assigned to technician": "تم تعيين الفني",
  "Device is fixed and ready": "الجهاز جاهز ومُصلح",
  "Are you sure you want to delete this technician?": "هل أنت متأكد من حذف هذا الفني؟",
  "Are you sure you want to delete this order?": "هل أنت متأكد من حذف هذا الطلب؟",
  "Delete this request?": "هل تريد حذف هذا الطلب؟",
  "No requests": "لا توجد طلبات",
  "Contacted": "تم التواصل",
  "Closed": "مغلق",
  "Mark Contacted": "وضع كمتواصل",
  "Close Request": "إغلاق الطلب",
  "Message": "الرسالة",
  "Select a request to view details": "اختر طلبًا لعرض التفاصيل",
  "Contact:": "جهة الاتصال:",
  "Devices:": "الأجهزة:",
  "Request Received": "تم استلام الطلب",
  "Thank you for choosing KBI Corporate. Our enterprise team has received your request and will contact you within 2 hours.": "شكرًا لاختيارك KBI للشركات. لقد استلم فريقنا طلبك وسيتواصل معك خلال ساعتين.",
  "Company Name": "اسم الشركة",
  "Company Email": "البريد الإلكتروني للشركة",
  "Contact Person": "جهة الاتصال",
  "Mobile Number": "رقم الجوال",
  "Device Count": "عدد الأجهزة",
  "Device Types": "أنواع الأجهزة",
  "Urgency": "درجة الأهمية",
  "Select Urgency Level": "اختر درجة الأهمية",
  "Normal (24-48h)": "عادي (24-48 ساعة)",
  "High (Same Day)": "عالي (نفس اليوم)",
  "Critical (Immediate - 2h)": "حرِج (فوري - 2 ساعة)",
  "Office Location / Area": "موقع المكتب / المنطقة",
  "Approx. number of devices": "العدد التقريبي للأجهزة",
  "Phones, Laptops, PC / Desktop, Printers, CCTV, TVs": "هواتف، لابتوبات، كمبيوتر مكتبي، طابعات، كاميرات مراقبة، تلفزيونات",
  "Full Name": "الاسم الكامل",
  "e.g. Tech Solutions Ltd": "مثال: شركة تك سوليوشنز",
  "e.g. Tomorrow 10AM": "مثال: غدًا الساعة 10 صباحًا",
  "Submit Request": "إرسال الطلب",
  "Request Additional Parts / Services": "طلب إضافة قطع/خدمات",
  "Part / Service Name": "اسم القطعة/الخدمة",
  "Category": "الفئة",
  "Spare Part": "قطعة غيار",
  "Additional Service": "خدمة إضافية",
  "Quantity": "الكمية",
  "Estimated Price (AED)": "السعر التقديري (درهم)",
  "Reason for Request": "سبب الطلب",
  "Optional Photo": "صورة اختيارية",
  "Pending Admin Approval": "بانتظار موافقة الإدارة",
  "Technician Requests": "طلبات الفنيين",
  "Approve Request": "الموافقة على الطلب",
  "Reject Request": "رفض الطلب",
  "Edit Price": "تعديل السعر",
  "Admin Notes": "ملاحظات الإدارة",
  "Request approved": "تمت الموافقة على الطلب",
  "Request rejected": "تم رفض الطلب",
  "Price updated by admin": "تم تحديث السعر بواسطة الإدارة",
  "New technician request submitted": "تم إرسال طلب جديد من الفني",
  "Waiting for Parts Approval": "بانتظار موافقة القطع",
  "Approved – Continue Repair": "تمت الموافقة – متابعة الإصلاح",
  "Notifications": "الإشعارات",
  "No notifications": "لا توجد إشعارات",
  "Invoice": "الفاتورة",
  "On-Site Repair Service": "خدمة الإصلاح في الموقع",
  "Invoice Number": "رقم الفاتورة",
  "Invoice Date": "تاريخ الفاتورة",
  "Customer Information": "بيانات العميل",
  "Service Address": "عنوان الخدمة",
  "Device Information": "بيانات الجهاز",
  "Device Type": "نوع الجهاز",
  "Serial Number (optional)": "الرقم التسلسلي (اختياري)",
  "Description": "الوصف",
  "Qty": "الكمية",
  "Unit Price (AED)": "سعر الوحدة (درهم)",
  "Total (AED)": "الإجمالي (درهم)",
  "Subtotal": "المجموع الفرعي",
  "VAT": "ضريبة القيمة المضافة",
  "Final Total Price (AED)": "الإجمالي النهائي (درهم)",
  "Warranty & Notes": "الضمان والملاحظات",
  "Warranty Period": "مدة الضمان",
  "Thank you for choosing KBI.": "شكرًا لاختيارك KBI.",
  "Customer Signature": "توقيع العميل",
  "Technician Signature": "توقيع الفني",
  "Generate Final Invoice": "إنشاء الفاتورة النهائية",
  "Preview Invoice": "معاينة الفاتورة",
  "Print Invoice": "طباعة الفاتورة",
  "Download as PDF": "تحميل كملف PDF",
  "Resend to Customer": "إعادة الإرسال إلى العميل",
  "Invoice Status": "حالة الفاتورة",
  "Finalize Invoice": "اعتماد الفاتورة",
  "Override reason": "سبب التعديل",
  "Override Edit": "تعديل بالإلغاء",
  "English": "الإنجليزية",
  "Arabic": "العربية",
  "EN + AR": "العربية + الإنجليزية",
  "Invoice Preview": "معاينة الفاتورة",
  "VAT Enabled": "تشغيل الضريبة",
  "VAT Rate": "نسبة الضريبة",
  "Disclaimer": "إخلاء المسؤولية",
  "Apple": "أبل",
  "Samsung": "سامسونج",
  "Xiaomi": "شاومي",
  "Huawei": "هواوي",
  "OPPO": "أوبو",
  "Vivo": "فيفو",
  "OnePlus": "ون بلس",
  "Google": "جوجل",
  "Apple MacBook": "أبل ماك بوك",
  "Dell": "ديل",
  "HP": "إتش بي",
  "Lenovo": "لينوفو",
  "ASUS": "أسوس",
  "Acer": "إيسر",
  "MSI": "إم إس آي",
  "Custom Build (PC Tower)": "تجميع مخصص (PC Tower)",
  "Canon": "كانون",
  "Epson": "إبسون",
  "Brother": "بروذر",
  "Sony": "سوني",
  "LG": "إل جي",
  "Hisense": "هايسنس",
  "TCL": "تي سي إل",
  "Philips": "فيليبس",
  "Panasonic": "باناسونيك",
  "Sharp": "شارب",
  "Hikvision": "هيك فيجن",
  "Dahua": "داهوا",
  "Uniview": "يوني فيو",
  "Ezviz": "إيزفيز",
  "CP Plus": "سي بي بلس",
  "IMOU": "إيمو",
  "TP-Link": "تي بي لينك",
  "Samsung CCTV": "سامسونج للمراقبة",
  "Other Brand": "علامة تجارية أخرى",
  "Samsung Galaxy Tab": "سامسونج جالاكسي تاب",
  "Cisco": "سيسكو",
  "Ubiquiti / UniFi": "يوبيكويتي / يوني فاي",
  "D-Link": "دي لينك",
  "Netgear": "نت جير",
  "Linksys": "لينكسيس",
  "Windows Support": "دعم ويندوز",
  "macOS Support": "دعم ماك",
  "Software & Apps": "البرامج والتطبيقات",
  "Remote Assistance": "المساعدة عن بعد",
  "Select time": "اختر الوقت",
  "Morning (9AM - 12PM)": "الصباح (9 صباحًا - 12 ظهرًا)",
  "Afternoon (12PM - 5PM)": "بعد الظهر (12 ظهرًا - 5 مساءً)",
  "Evening (5PM - 9PM)": "المساء (5 مساءً - 9 مساءً)",
  "As Soon As Possible": "في أسرع وقت ممكن",
  "home": "المنزل",
  "office": "المكتب",
  "In Progress": "قيد التنفيذ",
  "Waiting Parts": "بانتظار القطع",
  "Completed": "مكتمل",
  "Delivered": "تم التسليم",
  "Cancelled": "ملغى",
  "Pending": "قيد الانتظار",
  "unassigned": "غير معيّن",
  "Enterprise": "الشركات الكبيرة",
  "Healthcare": "المستشفيات",
  "Education": "الجامعات والمدارس",
  "Logistics": "اللوجستيات",
  "Hospitality": "الفنادق",
  "Government": "الجهات الحكومية",
  "Banking": "البنوك",
  "Retail": "المتاجر",
  "Hospitals": "المستشفيات",
  "Universities": "الجامعات",
  "Banks": "البنوك",
  "School": "المدارس",
  "Comprehensive Device Support": "دعم شامل للأجهزة",
  "Mobile Fleet": "أسطول الهواتف",
  "iPhone – Samsung – Huawei – Tablets": "أيفون – سامسونج – هواوي – أجهزة لوحية",
  "Laptops & Workstations": "اللابتوب ومحطات العمل",
  "Dell – HP – Lenovo – MacBook": "ديل – إتش بي – لينوفو – ماك بوك",
  "Office Equipment": "معدات المكتب",
  "Printers – Scanners – Plotters": "طابعات – ماسحات ضوئية – طابعات هندسية",
  "Monitors – Video Walls – Kiosks": "شاشات – جدران فيديو – أكشاك إلكترونية",
  "Security Systems": "أنظمة الأمان",
  "CCTV – Access Control – Biometrics": "كاميرات مراقبة – التحكم في الدخول – البصمة",
  "Meeting Rooms": "غرف الاجتماعات",
  "Smart TVs – Projectors – Audio": "تلفزيونات ذكية – أجهزة عرض – أنظمة صوتية",
  "Corporate Advantages": "مزايا الشركات",
  "Dedicated Account Manager": "مدير حساب مخصص",
  "Priority Service": "خدمة ذات أولوية",
  "On-Site Repairs": "إصلاح ميداني",
  "Maintenance Contracts": "عقود صيانة",
  "Asset Reporting": "تقارير الأصول",
  "Data Security": "أمن البيانات",
  "Schedule a": "حجز",
  "Corporate Technician": "فني للشركات",
  "Corporate form description": "املأ النموذج أدناه وسيتواصل معك فريقنا المختص بالشركات خلال أقل من 30 دقيقة.",
  "Trusted by": "موثوق من قبل",
  "Dedicated Account Manager Desc": "متابعة خاصة + نقطة اتصال واحدة لكل عميل من الشركات.",
  "Priority Service Desc": "خدمة فورية للشركات — دون انتظار مع أولوية في التنفيذ.",
  "On-Site Repairs Desc": "نأتي مباشرة إلى مقر شركتكم لتوفير الوقت والجهد.",
  "Maintenance Contracts Desc": "خطط صيانة مرنة تناسب احتياجات وحجم أعمالكم.",
  "Asset Reporting Desc": "تقارير دورية شاملة بالأعطال، الإصلاحات، وحالة الأجهزة.",
  "Data Security Desc": "بروتوكولات صارمة لضمان أمان وحماية بيانات الشركة.",
  "Battery Service": "خدمة البطارية",
  "Charging Port": "منفذ الشحن",
  "Data Migration": "نقل البيانات",
  "Hardware Repair": "إصلاح الأجهزة",
  "SSD/RAM Upgrades": "ترقية SSD/RAM",
  "OS Troubleshooting": "إصلاح مشاكل نظام التشغيل",
  "Performance Tuning": "تحسين الأداء",
  "Paper Jam Fix": "إصلاح انحشار الورق",
  "Toner/Cartridge": "الحبر / الخرطوشة",
  "Network Setup": "إعداد الشبكة",
  "Annual Maintenance": "الصيانة السنوية",
  "Panel Replacement": "استبدال الشاشة",
  "Power Issues": "مشاكل الطاقة",
  "Color Calibration": "معايرة الألوان",
  "Mounting": "التركيب",
  "Camera Installation": "تركيب الكاميرات",
  "DVR/NVR Config": "ضبط أجهزة DVR/NVR",
  "Cabling": "التمديدات",
  "System Upgrades": "ترقية الأنظمة",
  "Connectivity Issues": "مشاكل الاتصال",
  "Mounting Service": "خدمة التركيب",
  "Sound Systems": "أنظمة الصوت",
  "Conference Setup": "تجهيز قاعات المؤتمرات",
  "Years Experience": "سنوات خبرة",
  "Devices Repaired": "جهاز تم إصلاحه",
  "Satisfaction Rate": "نسبة الرضا",
  "Service Available": "الخدمة متاحة",
  "Our Mission": "مهمتنا",
  "Customer First": "العميل أولاً",
  "Quality Guarantee": "ضمان الجودة",
  "Our Mission Desc": "توفير خدمات إصلاح ميدانية سريعة وموثوقة واحترافية توفر لعملائنا الوقت والجهد.",
  "Customer First Desc": "نحن نضع رضا العملاء فوق كل اعتبار. ثقتكم هي أثمن أصولنا، ونحن نعمل بجد لكسبها كل يوم.",
  "Quality Guarantee Desc": "نحن نستخدم فقط قطع الغيار الأصلية أو عالية الجودة وندعم جميع إصلاحاتنا بضمان قوي لراحة بالكم.",
  "Free diagnosis when repair is approved": "فحص مجاني عند الموافقة على الإصلاح",
  "Original & high-quality spare parts": "قطع غيار أصلية وعالية الجودة",
  "3-6 months warranty on all repairs": "ضمان من 3 إلى 6 أشهر على جميع الإصلاحات",
  "Transparent pricing with no hidden fees": "أسعار شفافة بدون رسوم خفية",
  "Same-day service for most repairs": "خدمة في نفس اليوم لمعظم الإصلاحات",
  "Money-back guarantee if not satisfied": "ضمان استرداد الأموال إذا لم تكن راضيًا",
  "About Title Prefix": "عن",
  "KBI is Abu Dhabi's trusted on-site repair service provider. We bring professional device repair directly to your doorstep - whether it's your home, office, or anywhere in Abu Dhabi.": "KBI هي مزود خدمة الإصلاح الميداني الموثوق به في أبوظبي. نحن نقدم إصلاح الأجهزة الاحترافي مباشرة إلى باب منزلك - سواء كان ذلك في منزلك أو مكتبك أو في أي مكان في أبوظبي.",
  "Who We Are": "من نحن",
  "Founded with a simple mission: to make device repair convenient and hassle-free. We understand how frustrating it can be when your phone, laptop, or TV breaks down unexpectedly.": "تأسست بمهمة بسيطة: جعل إصلاح الأجهزة مريحًا وخاليًا من المتاعب. نحن نتفهم مدى الإحباط الذي يمكن أن تشعر به عندما يتعطل هاتفك أو لابتوبك أو تلفزيونك بشكل غير متوقع.",
  "That's why we created KBI - a mobile repair service that comes directly to you. Our team of certified technicians are equipped with the tools and expertise to fix most devices on the spot.": "لهذا السبب أنشأنا KBI - خدمة إصلاح متنقلة تأتي إليك مباشرة. فريقنا من الفنيين المعتمدين مجهز بالأدوات والخبرة اللازمة لإصلاح معظم الأجهزة في الموقع.",
  "We serve all areas of Abu Dhabi, including Al Reem Island, Khalifa City, Mohammed Bin Zayed City, Al Shamkha, and everywhere in between.": "نحن نخدم جميع مناطق أبوظبي، بما في ذلك جزيرة الريم، ومدينة خليفة، ومدينة محمد بن زايد، والشامخة، وكل مكان بينهما.",
  "Certified Technicians": "فنيون معتمدون",
  "Our technicians undergo rigorous training and certification programs to ensure they can handle any repair challenge. From the latest iPhone to gaming consoles, we've got you covered.": "يخضع فنيونا لبرامج تدريب واعتماد صارمة لضمان قدرتهم على التعامل مع أي تحدٍ في الإصلاح. من أحدث أجهزة iPhone إلى أجهزة الألعاب، نحن نوفر لك كل ما تحتاجه.",
  "Each technician specializes in specific device categories:": "يتخصص كل فني في فئات أجهزة محددة:",
  "Mobile phones & tablets (all brands)": "الهواتف المحمولة والأجهزة اللوحية (جميع الماركات)",
  "Laptops & computers (Windows & Mac)": "اللابتوب وأجهزة الكمبيوتر (ويندوز وماك)",
  "TVs, monitors & home electronics": "التلفزيونات والشاشات والإلكترونيات المنزلية",
  "CCTV systems & security equipment": "أنظمة كاميرات المراقبة ومعدات الأمان",
  "Our Values": "قيمنا",
  "Our Guarantees": "ضماناتنا",
  "Ready to Fix Your Device?": "هل أنت جاهز لإصلاح جهازك؟",
  "Book a Technician": "احجز فنيًا",
  "Company Presentation (PDF)": "عرض الشركة (PDF)",
  "Call Us": "اتصل بنا",
  "Speak directly with our support team": "تحدث مباشرة مع فريق الدعم لدينا",
  "Chat with us instantly": "تحدث معنا على الفور",
  "Send us an email anytime": "أرسل لنا بريدًا إلكترونيًا في أي وقت",
  "Send a message": "أرسل رسالة",
  "Contact Us": "تواصل معنا",
  "We're here to help! Reach out through any of the channels below or book a technician directly.": "نحن هنا للمساعدة! تواصل معنا عبر أي من القنوات أدناه أو احجز فنيًا مباشرة.",
  "Service Area": "منطقة الخدمة",
  "We provide on-site repair services across all areas of Abu Dhabi, including:": "نحن نقدم خدمات إصلاح ميدانية في جميع مناطق أبوظبي، بما في ذلك:",
  "Service Hours": "ساعات الخدمة",
  "Saturday - Thursday": "السبت - الخميس",
  "Friday": "الجمعة",
  "Emergency Service": "خدمة الطوارئ",
  "24/7 Available": "متاح على مدار الساعة طوال أيام الأسبوع",
  "For urgent repairs outside regular hours, contact us via WhatsApp or phone for emergency service availability.": "للإصلاحات العاجلة خارج الساعات العادية، اتصل بنا عبر الواتساب أو الهاتف لمعرفة توفر خدمة الطوارئ.",
  "Ready to Get Your Device Fixed?": "هل أنت جاهز لإصلاح جهازك؟",
  "Skip the wait. Book a certified technician to come to your location today. Fast, reliable, and guaranteed.": "تجنب الانتظار. احجز فنيًا معتمدًا ليأتي إلى موقعك اليوم. سريع وموثوق ومضمون.",
  "WhatsApp Us": "تواصل معنا عبر واتساب",
  "Privacy Policy": "سياسة الخصوصية",
  "All rights reserved.": "جميع الحقوق محفوظة.",
  "Best Repair Services in Abu Dhabi": "أفضل خدمات الإصلاح في أبوظبي",
  "KBI Repair Services": "KBI لخدمات الإصلاح",
  "Same-Day On-Site Service": "خدمة ميدانية في نفس اليوم",
  "contact@company.com": "contact@company.com",
  "Describe specific issues or requirements...": "صف المشاكل أو المتطلبات المحددة...",
  "Selected Issues": "المشاكل المختارة",
  "Location": "الموقع",
  "Terms & Conditions": "الشروط والأحكام",
  "Error": "خطأ",
  "Failed to create order. Please try again.": "فشل إنشاء الطلب. يرجى المحاولة مرة أخرى.",
  "Not an admin? Nice try 😄": "لست مشرفًا؟ محاولة جيدة 😄",
  "Please sign in to continue.": "يرجى تسجيل الدخول للمتابعة.",
  "Your account does not have admin access.": "حسابك لا يملك صلاحية المشرف.",
  "Go to Login": "الذهاب لتسجيل الدخول",
  "Back to Login": "العودة لتسجيل الدخول",
  "Install Admin App": "تثبيت تطبيق الإدارة",
  "Install App": "تثبيت التطبيق",
  "Installing...": "جارٍ التثبيت...",
  "Logout": "تسجيل الخروج",
  "Security": "الأمان",
  "Orders": "الطلبات",
  "Inventory": "المخزون",
  "Settings": "الإعدادات"
}

export function LanguageProvider({ children, initialLang }: { children: React.ReactNode; initialLang?: Lang }) {
  const [lang, setLang] = useState<Lang>(initialLang ?? "en")

  useEffect(() => {
    if (typeof document === "undefined") return
    document.documentElement.lang = lang
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
    if (typeof window !== "undefined") {
      window.localStorage.setItem("kbi-lang", lang)
      // Persist to cookie so server can detect language preference
      document.cookie = `kbi_lang=${lang};path=/;max-age=31536000;SameSite=Lax`
      document.documentElement.lang = lang
      document.documentElement.dir = lang === "ar" ? "rtl" : "ltr"
    }
  }, [lang])

  useEffect(() => {
    if (typeof window === "undefined") return
    const stored = window.localStorage.getItem("kbi-lang") as Lang | null
    if (stored === "ar" || stored === "en") {
      const id = requestAnimationFrame(() => setLang(stored))
      return () => cancelAnimationFrame(id)
    } else {
      // Default to English if no valid storage
      setLang("en")
    }
  }, [])

  useEffect(() => {
    if (process.env.NODE_ENV !== "production") return
    if (typeof window === "undefined") return
    let triggered = false
    const reload = () => {
      if (triggered) return
      triggered = true
      try {
        const c = (window as any).caches
        if (c && c.keys) {
          c
            .keys()
            .then((keys: string[]) => {
              for (const k of keys) c.delete(k).catch(() => { })
            })
            .catch(() => { })
        }
      } catch { }
      window.location.reload()
    }
    const onError = (e: Event) => {
      const t = e.target as any
      const isScript = t && (t.tagName === "SCRIPT" || t.localName === "script")
      const src = isScript ? t.src || "" : ""
      if (isScript && /:\/\/localhost:8081\/.*/.test(src)) {
        try { e.preventDefault() } catch { }
        return
      }
      if (isScript && src.includes("/_next/static/")) reload()
    }
    const onRejection = (e: PromiseRejectionEvent) => {
      const name = e.reason?.name || ""
      const msg = String(e.reason?.message || "")
      const isAbort = name === "AbortError" || /\?_rsc=/.test(msg)
      const isNavigationAbort = /net::ERR_ABORTED/i.test(msg) || /navigateDynamicallyWithNoPrefetch/.test(msg) || /__nextjs_devtools_config/.test(msg)
      if (isAbort) {
        try { e.preventDefault() } catch { }
        return
      }
      if (isNavigationAbort) {
        try { e.preventDefault() } catch { }
        return
      }
      if (name === "ChunkLoadError" || /Loading chunk .* failed/i.test(msg) || /Failed to load chunk/i.test(msg)) reload()
    }
    window.addEventListener("error", onError, true)
    window.addEventListener("unhandledrejection", onRejection)
    return () => {
      window.removeEventListener("error", onError, true)
      window.removeEventListener("unhandledrejection", onRejection)
    }
  }, [])

  const value = useMemo(() => ({ lang, setLang }), [lang])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  return useContext(LanguageContext)
}

export function useT() {
  const { lang } = useLanguage()
  return (key: string) => (lang === "ar" ? DICTIONARY[key] || key : ENGLISH_COPY[key] || key)
}
